### ISSUE TITLE
It detects spaces and code blocks as mistakes

### ISSUE THREAD

**Issue by Braweria** [Clemens-E/obsidian-languagetool-plugin#13]
The first example is tables. Here is an example:  

![image](https://user-images.githubusercontent.com/62669899/118598229-091cb180-b7ae-11eb-9af2-62a9826c66cf.png)

It detects the spaces, which makes the table prettier, as an error message. It can easily be ignored by the user, but it would be nice if that could get fixed somehow.  

My other example is code blocks, it wants to get rid of them completely.  
In the pop-up message, it says there is more than one space.  
![Animation](https://user-images.githubusercontent.com/62669899/118598577-9233e880-b7ae-11eb-81c6-0a8988a3a765.gif)
I believe generally stuff inside the code block should be ignored, unless the user specifically selects this text.

**Comment by Clemens-E** [comment]
This is the same problem, it wants to get rid of the code block because it already ignores the code block and then only sees two spaces.
I think for a clean solution this must be done in the Markdown parser.
But as soon as 0.0.7 is released, you could just disable the `WHITESPACE_RULE`, so LanguageTool ignores the repetition of whitespace (which is fairly common in markdown files)

**Comment by Clemens-E** [comment]
Hi, I just released Version 0.0.7
you can now go to the Plugins Settings and add `WHITESPACE_RULE` to "Disable Specific Rules"

**Comment by SkepticMystic** [comment]
Hey :) awesome work on this plugin, I'm loving the 0.1.0 update!
I have a similar error, but it is not the same. Even with disable `WHITESPACE_RULE`, I still get this suggestion showing up when using a comma immediately after a codeblock
![image](https://user-images.githubusercontent.com/70717676/123224832-710f9780-d4d2-11eb-8277-d44f79ae5555.png)

**Comment by Clemens-E** [comment]
thats because the "WHITESPACE_RULE" is responsible for repeated whitespaces, not for the placement of commas.
this way it does not flag markdown tables as errors

**Comment by SkepticMystic** [comment]
Makes sense. Then this is a different bug, I guess. Would you like me to make a new issue instead?

**Comment by mgmeyers** [comment]
Hey all, it turns out inline code was being collapsed down to a single space, causing this issue. This has been fixed in v0.1.2.
